In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("results.csv")
data

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,Result_team1
0,2/3/1900,Scotland,Wales,5,2,British Home Championship,Aberdeen,Scotland,False,Win
1,2/24/1900,Wales,Northern Ireland,2,0,British Home Championship,Llandudno,Wales,False,Win
2,3/3/1900,Northern Ireland,Scotland,0,3,British Home Championship,Belfast,Ireland,False,Lose
3,3/17/1900,Northern Ireland,England,0,2,British Home Championship,Dublin,Ireland,False,Lose
4,3/26/1900,Wales,England,1,1,British Home Championship,Cardiff,Wales,False,Draw
...,...,...,...,...,...,...,...,...,...,...
48759,12/12/2025,Jordan,Iraq,1,0,Arab Cup,Al Rayyan,Qatar,True,Win
48760,12/12/2025,Algeria,United Arab Emirates,1,1,Arab Cup,Al Khor,Qatar,True,Draw
48761,12/15/2025,Morocco,United Arab Emirates,3,0,Arab Cup,Al Rayyan,Qatar,True,Win
48762,12/15/2025,Saudi Arabia,Jordan,0,1,Arab Cup,Al Khor,Qatar,True,Lose
48763,12/18/2025,Jordan,Morocco,2,3,Arab Cup,Lusail,Qatar,True,Lose

In [3]:
x = data[["date","home_team","away_team","Result_team1"]]
x.tail()

             date     home_team             away_team Result_team1
48759  12/12/2025        Jordan                  Iraq          Win
48760  12/12/2025       Algeria  United Arab Emirates         Draw
48761  12/15/2025       Morocco  United Arab Emirates          Win
48762  12/15/2025  Saudi Arabia                Jordan         Lose
48763  12/18/2025        Jordan               Morocco         Lose

In [4]:
data1 = pd.read_csv("new filed.csv")
data1

,Match,Team1,Team2,Match_Date,Team1_Recent_form,Team2_Recent_form,Team1_rank,Team2_rank,Team1_Star_Player_Count,Team1_Top100_players,Team2_Star_Player_Count,Team2_Top100_players,Head_to_Head_Team1_result_percentage,Team1_Result,Team1_goalkeeper_rank,Team2_goalkeeper_rank
0,2002FrancevsSenagal,France,Senegal,5/31/2002,NaN,NaN,1,42,1,6,0,2,0.000,-1,3,19
1,2002UruguayvsDenmark,Uruguay,Denmark,6/1/2002,NaN,NaN,24,20,0,1,0,2,0.000,-1,14,9
2,2002DenmarkvsSenegal,Denmark,Senegal,6/6/2002,NaN,NaN,20,42,0,2,0,2,0.750,0,9,19
3,2002FrancevsUruguay,France,Uruguay,6/6/2002,NaN,NaN,1,24,1,6,0,1,0.375,0,3,14
4,2002DenmarkvsFrance,Denmark,France,6/11/2002,NaN,NaN,20,1,0,2,1,6,0.500,1,9,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,2022MorvsPor,Morocco,Portugal,12/10/2022,NaN,NaN,22,9,1,3,3,6,0.500,1,16,7
379,2022ArgvsCro,Argentina,Croatia,12/13/2022,NaN,NaN,3,12,3,6,2,4,0.500,1,5,10
380,2022FravsMor,France,Morocco,12/14/2022,NaN,NaN,4,22,4,8,1,3,0.800,1,4,16
381,2022_Final_ArgvsFra,Argentina,France,12/18/2022,NaN,NaN,3,4,3,6,4,8,0.625,0,5,4
382,2022CrovsMor,Croatia,Morocco,12/17/2022,NaN,NaN,12,22,2,4,1,3,0.500,1,10,16

In [ ]:
def get_recent(row):
    input_date = pd.to_datetime(row["Match_Date"])
    fi_team = row["Team1"]
    # fi_team2 = row["Team2"]

    # filter date 
    date_fill = x[pd.to_datetime(x["date"]) < input_date ]
    
    # filter for the home_team to fil team
    cond1 = (
        date_fill["home_team"] == fi_team

    )
    # filter for the away_team to fil team
    cond2 =(
        date_fill["away_team"] == fi_team
    )

    recent_form = date_fill[cond1 | cond2].tail()

    points = 0
    
    for r,i in recent_form.iterrows():
        if i["home_team"] == fi_team:

            if i["Result_team1"] == "Win":
                points = points + 1
            elif i["Result_team1"] == "Draw":
                points = points + 0.5 

        else:
            if i["Result_team1"] == "Lose":
                points = points +1
            elif i["Result_team1"] == "Draw":
                points = points + 0.5

    
    
    
    return points            

    
    
    


data1["Team1_Recent_form"] = data1.apply(
    get_recent,
    axis=1
)

In [9]:
data1

,Match,Team1,Team2,Match_Date,Team1_Recent_form,Team2_Recent_form,Team1_rank,Team2_rank,Team1_Star_Player_Count,Team1_Top100_players,Team2_Star_Player_Count,Team2_Top100_players,Head_to_Head_Team1_result_percentage,Team1_Result,Team1_goalkeeper_rank,Team2_goalkeeper_rank
0,2002FrancevsSenagal,France,Senegal,5/31/2002,3.5,NaN,1,42,1,6,0,2,0.000,-1,3,19
1,2002UruguayvsDenmark,Uruguay,Denmark,6/1/2002,2.5,NaN,24,20,0,1,0,2,0.000,-1,14,9
2,2002DenmarkvsSenegal,Denmark,Senegal,6/6/2002,4.0,NaN,20,42,0,2,0,2,0.750,0,9,19
3,2002FrancevsUruguay,France,Uruguay,6/6/2002,2.5,NaN,1,24,1,6,0,1,0.375,0,3,14
4,2002DenmarkvsFrance,Denmark,France,6/11/2002,4.5,NaN,20,1,0,2,1,6,0.500,1,9,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,2022MorvsPor,Morocco,Portugal,12/10/2022,4.0,NaN,22,9,1,3,3,6,0.500,1,16,7
379,2022ArgvsCro,Argentina,Croatia,12/13/2022,3.5,NaN,3,12,3,6,2,4,0.500,1,5,10
380,2022FravsMor,France,Morocco,12/14/2022,4.0,NaN,4,22,4,8,1,3,0.800,1,4,16
381,2022_Final_ArgvsFra,Argentina,France,12/18/2022,4.5,NaN,3,4,3,6,4,8,0.625,0,5,4
382,2022CrovsMor,Croatia,Morocco,12/17/2022,2.5,NaN,12,22,2,4,1,3,0.500,1,10,16

In [10]:
def get_recent1(row):
    input_date = pd.to_datetime(row["Match_Date"])
    fi_team2 = row["Team2"]
    

    # filter date 
    date_fill = x[pd.to_datetime(x["date"]) < input_date ]
    
    # filter for the home_team to fil team
    cond1 = (
        date_fill["home_team"] == fi_team2

    )
    # filter for the away_team to fil team
    cond2 =(
        date_fill["away_team"] == fi_team2
    )

    recent_form = date_fill[cond1 | cond2].tail()

    points = 0
    
    for _,i in recent_form.iterrows():
        if i["home_team"] == fi_team2:

            if i["Result_team1"] == "Win":
                points = points + 1
            elif i["Result_team1"] == "Draw":
                points = points + 0.5 

        else:
            if i["Result_team1"] == "Lose":
                points = points +1
            elif i["Result_team1"] == "Draw":
                points = points + 0.5

    
    
    
    return points            

    
    
    


data1["Team2_Recent_form"] = data1.apply(
    get_recent1,
    axis=1
)
data1

,Match,Team1,Team2,Match_Date,Team1_Recent_form,Team2_Recent_form,Team1_rank,Team2_rank,Team1_Star_Player_Count,Team1_Top100_players,Team2_Star_Player_Count,Team2_Top100_players,Head_to_Head_Team1_result_percentage,Team1_Result,Team1_goalkeeper_rank,Team2_goalkeeper_rank
0,2002FrancevsSenagal,France,Senegal,5/31/2002,3.5,3.5,1,42,1,6,0,2,0.000,-1,3,19
1,2002UruguayvsDenmark,Uruguay,Denmark,6/1/2002,2.5,4.0,24,20,0,1,0,2,0.000,-1,14,9
2,2002DenmarkvsSenegal,Denmark,Senegal,6/6/2002,4.0,3.5,20,42,0,2,0,2,0.750,0,9,19
3,2002FrancevsUruguay,France,Uruguay,6/6/2002,2.5,2.5,1,24,1,6,0,1,0.375,0,3,14
4,2002DenmarkvsFrance,Denmark,France,6/11/2002,4.5,2.0,20,1,0,2,1,6,0.500,1,9,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,2022MorvsPor,Morocco,Portugal,12/10/2022,4.0,4.0,22,9,1,3,3,6,0.500,1,16,7
379,2022ArgvsCro,Argentina,Croatia,12/13/2022,3.5,3.0,3,12,3,6,2,4,0.500,1,5,10
380,2022FravsMor,France,Morocco,12/14/2022,4.0,4.0,4,22,4,8,1,3,0.800,1,4,16
381,2022_Final_ArgvsFra,Argentina,France,12/18/2022,4.5,4.0,3,4,3,6,4,8,0.625,0,5,4
382,2022CrovsMor,Croatia,Morocco,12/17/2022,2.5,3.5,12,22,2,4,1,3,0.500,1,10,16

In [23]:
dp_lit=["Match","Team1","Team2","Match_Date"]
y = data1[["Team1_Recent_form","Team2_Recent_form","Team1_rank","Team2_rank","Team1_Star_Player_Count","Team1_Top100_players","Team2_Star_Player_Count","Team2_Top100_players","Head_to_Head_Team1_result_percentage","Team1_Result","Team1_goalkeeper_rank","Team2_goalkeeper_rank"]]


y.corr()["Team1_Result"]

Team1_Recent_form                       0.236558
Team2_Recent_form                      -0.195546
Team1_rank                             -0.276599
Team2_rank                              0.256509
Team1_Star_Player_Count                 0.302143
Team1_Top100_players                    0.342584
Team2_Star_Player_Count                -0.260410
Team2_Top100_players                   -0.295892
Head_to_Head_Team1_result_percentage    0.490687
Team1_Result                            1.000000
Team1_goalkeeper_rank                  -0.368429
Team2_goalkeeper_rank                   0.364203
Name: Team1_Result, dtype: float64

In [12]:
date2 = "2022-12-14"
input_date = pd.to_datetime(date2)
fi_team1 = "France"
# fi_team2 = row["Team2"]

    # filter date 
date_fill = x[pd.to_datetime(x["date"]) < input_date ]
    
    # filter for the home_team to fil team
cond1 = (
        date_fill["home_team"] == fi_team1

    )
    # filter for the away_team to fil team
cond2 =(
        date_fill["away_team"] == fi_team1
    )

recent_form = date_fill[cond1 | cond2].tail()
recent_form

             date home_team  away_team Result_team1
45554  11/22/2022    France  Australia          Win
45570  11/26/2022    France    Denmark          Win
45586  11/30/2022   Tunisia     France          Win
45597   12/4/2022    France     Poland          Win
45607  12/10/2022   England     France         Lose